name: MAUI Unit Tests

on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
      - develop
      - 'feature/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI iOS workload
        run: dotnet workload install maui-ios

      - name: Restore dependencies
        run: dotnet restore Grocery.App/Grocery.App.csproj

#      - name: Build iOS
#        run: dotnet build Grocery.App/Grocery.App.csproj -f net8.0-ios --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test TestCore/TestCore.csproj --configuration Release
